baseURL: https://www.lorrrie.com/
languageCode: en-us
title: untimely
theme: PaperMod

params:
  homeInfoParams:
    Title: HIDE BEHIND A PAINTED SMILE
    Content: THE STORY MAY COME TO THE END
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
