baseURL: https://www.lorrrie.com/
languageCode: en-us
title: UNWANTED
theme: PaperMod

params:
  homeInfoParams:
    Title: I AM JUST A CLOWN
    Content: NOBODY NEEDS ME
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
