baseURL: https://www.lorrrie.com/
languageCode: en-us
title: HOME
theme: PaperMod

params:
  homeInfoParams:
    Title: The Stories of Lorrie and Woody
    Content: YOU ARE (NOT) ALONE.
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: true
  defaultTheme: dark
  disableThemeToggle: true
