baseURL: https://www.lorrrie.com/
languageCode: en-us
title: Home
theme: PaperMod

params:
  homeInfoParams:
    Title: The Stories of Lorrie and Woody
    Content: You are always my LOVE, since the very first day.
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: true
  env: production
  assets:
    disableHLJS: true
  defaultTheme: light
  disableThemeToggle: true
