baseURL: https://www.lorrrie.com/
languageCode: en-us
title: untimely
theme: PaperMod

params:
  homeInfoParams:
    Title: I LOVE YOU
    Content: MORE THAN YOU'LL EVER KNOW
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
