baseURL: https://www.lorrrie.com/
languageCode: en-us
title: HOME
theme: PaperMod

params:
  homeInfoParams:
    Title: I WON'T BOTHER YOU ANYMORE
    Content: YOU CAN HAVE A BETTER LIFE WITHOUT ME
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
