baseURL: https://www.lorrrie.com/
languageCode: en-us
title:
theme: PaperMod

params:
  homeInfoParams:
    Title: 可能我就是配不上你吧
    Content: 我尽力了，我付出了，我输得彻彻底底
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
