baseURL: https://www.lorrrie.com/
languageCode: en-us
title: untimely
theme: PaperMod

params:
  homeInfoParams:
    Title: THE STORIES OF LORRIE AND WOODY
    Content: I LOVE YOU
  ShowToc: true
  TocOpen: true
  ShowCodeCopyButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: true
